export { default as GithubLogo } from './gihub_logo.svg'
export { default as ReactLogo } from './react_logo.svg'
export { default as TopIcon } from './bottom.svg'
export { default as BottomIcon } from './top.svg'
export { default as Arrow } from './arrow.svg'
export { default as Pill } from './pill.svg'
export { default as Test } from './test.svg'
export * as IconCollection from 'public/static/icon'
