export interface AggressivePropsType {
  aggressive:
    | 'headline_oneline_001'
    | 'headline_oneline_002'
    | 'headline_oneline_003'
    | 'headline_oneline_004'
    | 'headline_oneline_005'
    | 'headline_oneline_006'
    | 'headline_multiline_001'
    | 'headline_multiline_002'
    | 'body_oneline_000'
    | 'body_oneline_001'
    | 'body_oneline_002'
    | 'body_oneline_003'
    | 'body_oneline_004'
    | 'body_oneline_005'
    | 'body_oneline_006'
    | 'body_multiline_000'
    | 'body_multiline_001'
    | 'body_multiline_002'
    | 'body_multiline_003'
    | 'body_multiline_004'
    | 'body_multiline_005'
    | 'button_000'
    | 'button_001'
    | 'tab_001'
    | 'tab_002'
    | 'tab_003'
    | 'caption_large'
    | 'caption_medium'
    | 'caption_small'
    | 'montserratAlternates_Bold_001'
    | 'montserratAlternates_Bold_002'
    | 'montserratAlternates_Bold_003'
    | 'montserratAlternates_Medium_001'
    | 'montserratAlternates_Medium_002'
    | 'montserratAlternates_Medium_003'
    | 'montserratAlternates_Regular_001'
    | 'montserratAlternates_Regular_002'
    | 'montserratAlternates_Regular_003'
    | 'montserratAlternates_light'
}

export interface VariantPropsType {
  variant:
    | 'h1'
    | 'h2'
    | 'h3'
    | 'h4'
    | 'h5'
    | 'h6'
    | 'p'
    | 'caption'
    | 'span'
    | 'div'
}
