export { default as Badge } from 'components/common/Badge'
export { default as Footer } from 'components/common/Footer'
export { default as Header } from 'components/common/Header'
export { default as Label } from 'components/common/Label'
export { default as Layout } from 'components/common/Layout'
export { default as Typography } from 'components/common/Typography'
export { default as LargeBtn } from 'components/common/Button/LargeButton'

export * as Lottie from 'components/common/Lottie'
export * as StyledLayout from './StyledLayout'
