#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# 현재 Branch
BRANCH_NAME=`git rev-parse --abbrev-ref HEAD`

# 색상 코드
RED='\033[1;31m'
GREEN='\033[1;32m'
BOLD='\033[1m'
RESET='\033[0m'
YELLOW='\033[1;33m'
BLUE='\033[1;34m'

echo "${YELLOW}Current Branch Name"
echo "${YELLOW}$BRANCH_NAME"


# 개발환경에서 Feature Merge 진행 시 동작
if [ "$BRANCH_NAME" = "dev"  ]; then
  echo "${BOLD}Feature branch merged into develop. Running automation...${RESET}"

  if [ $? -eq 0 ]; then
    # DEV BRANCH 로 자동 배포
    git push origin dev

    if [ $? -eq 0 ]; then
      echo "${GREEN}Merge into main successful. Pushing to main...${RESET}"
    else
      echo "${RED}Merge into main failed. Aborting the push to main.${RESET}"
    fi
  else
    echo "${RED}Build failed. Aborting the push to develop.${RESET}"
  fi
fi
